### ISSUE TITLE
When i try to open the jar file, it says: "Brocken Manifest"

### ISSUE THREAD

**Issue by cypcypcyp2** [Dan95363/worldshardestgame#2]

**Comment by danspage** [comment]
I have no idea, I'm really sorry. This project is super old and I haven't played with it in a long time.

**Comment by cypcypcyp2** [comment]
Can you try to fix something?

**Comment by danspage** [comment]
You may want to try creating a new Manifest.mf that points to the main class, then compiling it yourself.

**Comment by danspage** [comment]
Also at this point, you're in the same boat as me in terms of knowledge of the code, I'd as well just be reverse engineering it and googling errors.

**Comment by cypcypcyp2** [comment]
So... you can fix?

**Comment by danspage** [comment]
If you want it fixed, you're going to have to do it.

**Comment by cypcypcyp2** [comment]
Lol i downloaded it on my pc and it worked

чт, 19 нояб. 2020 г., 20:22 danspage <notifications@github.com>:

**Comment by cypcypcyp2** [comment]
Lol i downloaded it on my pc and it worked

**Comment by cypcypcyp2** [comment]
But there are only first two lvls lol
